language: node_js

node_js:
  - '8'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - node --version
  - yarn --version

install:
  - yarn --no-lockfile

os:
  - osx
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

script:
  - yarn test

cache: yarn
